language: php

php:
    - 5.6
    - 5.5
    - 5.4
    - hhvm-nightly

matrix:
    allow_failures:
        - php: hhvm-nightly

before_script:
    - composer self-update
    - composer install
    - mv config-example.php config.php
    - mysql -e 'create database mydb;'
    - ./infuse schema install

script:
    - mkdir -p build/logs
    - phpunit

after_script:
    - vendor/bin/coveralls