language: php

php:
    - 5.6
    - 5.5
    - 5.4
    - hhvm

before_script:
    - composer install
    - mv config-example.php config.php
    - mysql -e 'create database mydb;'
    - php infuse migrate

script:
    - mkdir -p build/logs
    - phpunit

after_script:
    - vendor/bin/coveralls