language: php
php:
    - 5.6
    - 5.5
    - 5.4
    - hhvm

sudo:
    false

cache:
  directories:
    - vendor

before_script:
    - composer install
    - mv config-example.php config.php
    - mysql -e 'create database mydb;'
    - php infuse migrate
    - mkdir -p build/logs

script:
    - phpunit

after_script:
    - vendor/bin/coveralls